// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.produban.openbus.console.domain;

import com.produban.openbus.console.domain.CamposOrigen;
import com.produban.openbus.console.domain.CamposOrigenDataOnDemand;
import com.produban.openbus.console.repository.CamposOrigenRepository;
import com.produban.openbus.console.service.CamposOrigenService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CamposOrigenDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CamposOrigenDataOnDemand: @Component;
    
    private Random CamposOrigenDataOnDemand.rnd = new SecureRandom();
    
    private List<CamposOrigen> CamposOrigenDataOnDemand.data;
    
    @Autowired
    CamposOrigenService CamposOrigenDataOnDemand.camposOrigenService;
    
    @Autowired
    CamposOrigenRepository CamposOrigenDataOnDemand.camposOrigenRepository;
    
    public CamposOrigen CamposOrigenDataOnDemand.getNewTransientCamposOrigen(int index) {
        CamposOrigen obj = new CamposOrigen();
        setNombreCampo(obj, index);
        setTipoCampo(obj, index);
        return obj;
    }
    
    public void CamposOrigenDataOnDemand.setNombreCampo(CamposOrigen obj, int index) {
        String nombreCampo = "nombreCampo_" + index;
        obj.setNombreCampo(nombreCampo);
    }
    
    public void CamposOrigenDataOnDemand.setTipoCampo(CamposOrigen obj, int index) {
        String tipoCampo = "tipoCampo_" + index;
        obj.setTipoCampo(tipoCampo);
    }
    
    public CamposOrigen CamposOrigenDataOnDemand.getSpecificCamposOrigen(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CamposOrigen obj = data.get(index);
        Long id = obj.getId();
        return camposOrigenService.findCamposOrigen(id);
    }
    
    public CamposOrigen CamposOrigenDataOnDemand.getRandomCamposOrigen() {
        init();
        CamposOrigen obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return camposOrigenService.findCamposOrigen(id);
    }
    
    public boolean CamposOrigenDataOnDemand.modifyCamposOrigen(CamposOrigen obj) {
        return false;
    }
    
    public void CamposOrigenDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = camposOrigenService.findCamposOrigenEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CamposOrigen' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CamposOrigen>();
        for (int i = 0; i < 10; i++) {
            CamposOrigen obj = getNewTransientCamposOrigen(i);
            try {
                camposOrigenService.saveCamposOrigen(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            camposOrigenRepository.flush();
            data.add(obj);
        }
    }
    
}
