// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.produban.openbus.console.domain;

import com.produban.openbus.console.domain.CamposOrigenDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CamposOrigenDataOnDemand_Roo_Configurable {
    
    declare @type: CamposOrigenDataOnDemand: @Configurable;
    
}
