// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.produban.openbus.console.domain;

import com.produban.openbus.console.domain.MetricaBatch;
import java.io.Serializable;

privileged aspect MetricaBatch_Roo_Serializable {
    
    declare parents: MetricaBatch implements Serializable;
    
    private static final long MetricaBatch.serialVersionUID = 1L;
    
}
