// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.produban.openbus.console.domain;

import com.produban.openbus.console.domain.QueryCep;

privileged aspect QueryCep_Roo_Serializable {
    
    private static final long QueryCep.serialVersionUID = 1L;
    
}
